// <auto-generated />
namespace ADKT_WebProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBrandImgToBrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBrandImgToBrand));
        
        string IMigrationMetadata.Id
        {
            get { return "202107260547466_AddBrandImgToBrand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
